//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topppro.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ent_PackageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ent_PackageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topppro.Entities.Resources.Ent_PackageResource", typeof(Ent_PackageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string _Caption {
            get {
                return ResourceManager.GetString("_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Product.
        /// </summary>
        public static string Entity_ChildProduct {
            get {
                return ResourceManager.GetString("Entity_ChildProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Entity_Enabled {
            get {
                return ResourceManager.GetString("Entity_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Attribute.
        /// </summary>
        public static string Entity_InheritAttribute {
            get {
                return ResourceManager.GetString("Entity_InheritAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Bullet.
        /// </summary>
        public static string Entity_InheritBullet {
            get {
                return ResourceManager.GetString("Entity_InheritBullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include HiRes.
        /// </summary>
        public static string Entity_InheritHiRes {
            get {
                return ResourceManager.GetString("Entity_InheritHiRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Manual.
        /// </summary>
        public static string Entity_InheritManual {
            get {
                return ResourceManager.GetString("Entity_InheritManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Product.
        /// </summary>
        public static string Entity_ParentProduct {
            get {
                return ResourceManager.GetString("Entity_ParentProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Entity_Priority {
            get {
                return ResourceManager.GetString("Entity_Priority", resourceCulture);
            }
        }
    }
}
