//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topppro.WebSite.Areas.Humanist.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topppro.WebSite.Areas.Humanist.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Add_To_Compare {
            get {
                return ResourceManager.GetString("Add_To_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Compare_Panel_Clear_Button {
            get {
                return ResourceManager.GetString("Compare_Panel_Clear_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare_Panel_Compare_Button {
            get {
                return ResourceManager.GetString("Compare_Panel_Compare_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items To Compare.
        /// </summary>
        public static string Compare_Panel_Title {
            get {
                return ResourceManager.GetString("Compare_Panel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We apologize for your inconvenience, but this request could not be processed..
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s an error..
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi-Res Pics.
        /// </summary>
        public static string HiRes_Pics {
            get {
                return ResourceManager.GetString("HiRes_Pics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download here the DMX24.4 Firmware Update (v 2.9) 16mb.
        /// </summary>
        public static string Mixers_Detail_Dmx244_Firmware_Download {
            get {
                return ResourceManager.GetString("Mixers_Detail_Dmx244_Firmware_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMX24.4 Firmware Update Instructions.
        /// </summary>
        public static string Mixers_Detail_Dmx244_Firmware_Instructions {
            get {
                return ResourceManager.GetString("Mixers_Detail_Dmx244_Firmware_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our new digital mixer is designed primarily for LIVE Audio Applications for the customer who wants all the power &amp; convenience digital processing &amp; instant recall offers, without giving up the familiarity, affordability &amp; ease of use of a traditional analog-style live mixer. Our digital mixer is powerful, affordable &amp; very easy to use!.
        /// </summary>
        public static string Mixers_Detail_Dmx244_Message {
            get {
                return ResourceManager.GetString("Mixers_Detail_Dmx244_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;BLUETOOTH!! &lt;/strong&gt;NOW AVAILABLE  WITH ORDER.
        /// </summary>
        public static string Mixers_Index_Mx_Bluetooth {
            get {
                return ResourceManager.GetString("Mixers_Index_Mx_Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed for live mixing.
        /// </summary>
        public static string Mixers_Index_Mx_Digital_Live_Mixing {
            get {
                return ResourceManager.GetString("Mixers_Index_Mx_Digital_Live_Mixing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;E-CS&lt;/b&gt; Ethernet Module..
        /// </summary>
        public static string Modules_HiRes_E_Cs {
            get {
                return ResourceManager.GetString("Modules_HiRes_E_Cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-ARK&lt;/b&gt; Microphone Preamplifier.
        /// </summary>
        public static string Modules_HiRes_Tac_Ark {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Ark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-BT2.1B&lt;/b&gt; Bluetooth Audio Receiver..
        /// </summary>
        public static string Modules_HiRes_Tac_Bt2 {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Bt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-MP3-R&lt;/b&gt; Records sounds to an USB key..
        /// </summary>
        public static string Modules_HiRes_Tac_Mp3_R {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Mp3_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-MP3-S&lt;/b&gt; Displays song title on display..
        /// </summary>
        public static string Modules_HiRes_Tac_Mp3_S {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Mp3_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-MP3-T&lt;/b&gt; Displays track number on display..
        /// </summary>
        public static string Modules_HiRes_Tac_Mp3_T {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Mp3_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-MX DSP&lt;/b&gt; 24-Bit FX Processor..
        /// </summary>
        public static string Modules_HiRes_Tac_Mx_Dsp {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Mx_Dsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-MX EQ&lt;/b&gt; 9 Band Graphic EQ..
        /// </summary>
        public static string Modules_HiRes_Tac_Mx_Eq {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Mx_Eq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-TMW 2.4R&lt;/b&gt; 2.4GHz Digital Wireless Receiver..
        /// </summary>
        public static string Modules_HiRes_Tac_Tmw {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Tmw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000W class D amplification.
        /// </summary>
        public static string Packs_Index_i4K_2000W {
            get {
                return ResourceManager.GetString("Packs_Index_i4K_2000W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our new &lt;b&gt;SOHO V4/8&lt;/b&gt; systems offer   uncompromising high quality pro audio in a highly efficient low profile footprint. The perfect choice for intimate to mid size spaces for groups or installation. With its sleek modern look, wood satellite columns and subwoofer finished in our special &lt;b&gt;SOHO&lt;/b&gt; paint process, and with an impressive total of 1400W (peak) in a stereo configuration, &lt;b&gt;SOHO&lt;/b&gt; excels where it counts, in the way it sounds. &lt;br/&gt;&lt;br/&gt; Available in two configurations,   &lt;b&gt;SOHO V4 &lt;/b&gt;wi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Packs_Index_Soho_Message {
            get {
                return ResourceManager.GetString("Packs_Index_Soho_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducing: &lt;b&gt;Topp Pro SOHO V4/V8 PA Systems&lt;/b&gt;.
        /// </summary>
        public static string Packs_Index_Soho_Subtitle {
            get {
                return ResourceManager.GetString("Packs_Index_Soho_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Sound…&lt;br /&gt;No Strings Attached!.
        /// </summary>
        public static string Packs_Index_Soho_Title {
            get {
                return ResourceManager.GetString("Packs_Index_Soho_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAC Modules are compatible with the following models.
        /// </summary>
        public static string Processors_Index_Tac_Compatibility {
            get {
                return ResourceManager.GetString("Processors_Index_Tac_Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove_From_Compare {
            get {
                return ResourceManager.GetString("Remove_From_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available in 2 versions: one for Passive and the other for Active enclosures. Allows mounting 2 x i28H cabinets on a Topp Pro subwoofer.&lt;br/&gt;
        ///The bracket combines two i28H satellite cabinets mounted on a custom tooled array-style bracket (which allows multi-angle positioning of the two satellites) providing a very versatile application-specific coverage..
        /// </summary>
        public static string Speakers_Detail_SArray_Message {
            get {
                return ResourceManager.GetString("Speakers_Detail_SArray_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building on the success of our original KS Series &amp; their highly acclaimed signature sound, &lt;strong&gt;KS CS Series&lt;/strong&gt; offers customers two new significant benefits: The ability to create your own sound voicing for the cabinet via Ethernet port or Wi-Fi, and the ability to receive wireless audio.&lt;br /&gt;&lt;strong&gt;KS CS Series&lt;/strong&gt; includes a series of professionally painted active wood cabinets with onboard DSP processor, available in 8” Active, 10” Active, 12” Active, 15” Active, 215” Active, 15” Active [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Speakers_Index_Ks_Message {
            get {
                return ResourceManager.GetString("Speakers_Index_Ks_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducing: &lt;strong&gt;Topp Pro KS CS Series&lt;/strong&gt;.
        /// </summary>
        public static string Speakers_Index_Ks_Subtitle {
            get {
                return ResourceManager.GetString("Speakers_Index_Ks_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Sound…&lt;br /&gt;No Strings Attached!.
        /// </summary>
        public static string Speakers_Index_Ks_Title {
            get {
                return ResourceManager.GetString("Speakers_Index_Ks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manual.
        /// </summary>
        public static string User_Manual {
            get {
                return ResourceManager.GetString("User_Manual", resourceCulture);
            }
        }
    }
}
