//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Objects;
using System.Data.EntityClient;
using Topppro.Entities;

namespace Topppro.Repositories
{
    public partial class ToppproEntities : ObjectContext
    {
        public const string ConnectionString = "name=ToppproEntities";
        public const string ContainerName = "ToppproEntities";
    
        #region Constructors
    
        public ToppproEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ToppproEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ToppproEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Attribute> Attribute
        {
            get { return _attribute  ?? (_attribute = CreateObjectSet<Attribute>("Attribute")); }
        }
        private ObjectSet<Attribute> _attribute;
    
        public ObjectSet<Category> Category
        {
            get { return _category  ?? (_category = CreateObjectSet<Category>("Category")); }
        }
        private ObjectSet<Category> _category;
    
        public ObjectSet<Culture> Culture
        {
            get { return _culture  ?? (_culture = CreateObjectSet<Culture>("Culture")); }
        }
        private ObjectSet<Culture> _culture;
    
        public ObjectSet<Serie> Serie
        {
            get { return _serie  ?? (_serie = CreateObjectSet<Serie>("Serie")); }
        }
        private ObjectSet<Serie> _serie;
    
        public ObjectSet<Model> Model
        {
            get { return _model  ?? (_model = CreateObjectSet<Model>("Model")); }
        }
        private ObjectSet<Model> _model;
    
        public ObjectSet<Product> Product
        {
            get { return _product  ?? (_product = CreateObjectSet<Product>("Product")); }
        }
        private ObjectSet<Product> _product;

        #endregion
    }
}
