//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topppro.Repositories
{
    using Topppro.Entities;
    using Attribute = Topppro.Entities.Attribute;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToppproEntities : DbContext
    {
        public ToppproEntities()
            : base("name=ToppproEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assn_CategorySerie> Assn_CategorySerie { get; set; }
        public virtual DbSet<Assn_CategorySerieProduct> Assn_CategorySerieProduct { get; set; }
        public virtual DbSet<Attribute> Attribute { get; set; }
        public virtual DbSet<Bullet> Bullet { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Culture> Culture { get; set; }
        public virtual DbSet<Distributor> Distributor { get; set; }
        public virtual DbSet<Download> Download { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<Platform> Platform { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Serie> Serie { get; set; }
    }
}
