//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topppro.WebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topppro.WebSite.Resources.ImageResource", typeof(ImageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/amps-slider-1.jpg.
        /// </summary>
        public static string Amp_Slider_1 {
            get {
                return ResourceManager.GetString("Amp_Slider_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/amps-slider-2.jpg.
        /// </summary>
        public static string Amp_Slider_2 {
            get {
                return ResourceManager.GetString("Amp_Slider_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/amps-slider-3.jpg.
        /// </summary>
        public static string Amp_Slider_3 {
            get {
                return ResourceManager.GetString("Amp_Slider_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/appstore-apps.jpg.
        /// </summary>
        public static string AppStore_Apps {
            get {
                return ResourceManager.GetString("AppStore_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/appstore-apps-up.jpg.
        /// </summary>
        public static string AppStore_Apps_Up {
            get {
                return ResourceManager.GetString("AppStore_Apps_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/back-bottom.jpg.
        /// </summary>
        public static string Back_Bottom {
            get {
                return ResourceManager.GetString("Back_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/back-top.jpg.
        /// </summary>
        public static string Back_Top {
            get {
                return ResourceManager.GetString("Back_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/bluetoth-certificates.jpg.
        /// </summary>
        public static string Bluetooth_Certificates {
            get {
                return ResourceManager.GetString("Bluetooth_Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/bluetoth-certificates-up.jpg.
        /// </summary>
        public static string Bluetooth_Certificates_Up {
            get {
                return ResourceManager.GetString("Bluetooth_Certificates_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/bottom.jpg.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/catalog-download.jpg.
        /// </summary>
        public static string Catalog_Download {
            get {
                return ResourceManager.GetString("Catalog_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/catalog-download-up.jpg.
        /// </summary>
        public static string Catalog_Download_Up {
            get {
                return ResourceManager.GetString("Catalog_Download_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs1.jpg.
        /// </summary>
        public static string Cs_1 {
            get {
                return ResourceManager.GetString("Cs_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs2.jpg.
        /// </summary>
        public static string Cs_2 {
            get {
                return ResourceManager.GetString("Cs_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs3.jpg.
        /// </summary>
        public static string Cs_3 {
            get {
                return ResourceManager.GetString("Cs_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs-appstore.jpg.
        /// </summary>
        public static string Cs_AppStore {
            get {
                return ResourceManager.GetString("Cs_AppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs-slider-1.jpg.
        /// </summary>
        public static string Cs_Slider_1 {
            get {
                return ResourceManager.GetString("Cs_Slider_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs-slider-2.jpg.
        /// </summary>
        public static string Cs_Slider_2 {
            get {
                return ResourceManager.GetString("Cs_Slider_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs-slider-3.jpg.
        /// </summary>
        public static string Cs_Slider_3 {
            get {
                return ResourceManager.GetString("Cs_Slider_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs-slider-4.jpg.
        /// </summary>
        public static string Cs_Slider_4 {
            get {
                return ResourceManager.GetString("Cs_Slider_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs-slider-5.jpg.
        /// </summary>
        public static string Cs_Slider_5 {
            get {
                return ResourceManager.GetString("Cs_Slider_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs-slider-6.jpg.
        /// </summary>
        public static string Cs_Slider_6 {
            get {
                return ResourceManager.GetString("Cs_Slider_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs-sound.jpg.
        /// </summary>
        public static string Cs_Sound {
            get {
                return ResourceManager.GetString("Cs_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/cs-sound-up.jpg.
        /// </summary>
        public static string Cs_Sound_Up {
            get {
                return ResourceManager.GetString("Cs_Sound_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/hires-bottom.jpg.
        /// </summary>
        public static string HiRes_Bottom {
            get {
                return ResourceManager.GetString("HiRes_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/hires-top.jpg.
        /// </summary>
        public static string HiRes_Top {
            get {
                return ResourceManager.GetString("HiRes_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/install-slider-1.jpg.
        /// </summary>
        public static string Install_Slider_1 {
            get {
                return ResourceManager.GetString("Install_Slider_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/install-slider-2.jpg.
        /// </summary>
        public static string Install_Slider_2 {
            get {
                return ResourceManager.GetString("Install_Slider_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/install-slider-3.jpg.
        /// </summary>
        public static string Install_Slider_3 {
            get {
                return ResourceManager.GetString("Install_Slider_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/install-slider-4.jpg.
        /// </summary>
        public static string Install_Slider_4 {
            get {
                return ResourceManager.GetString("Install_Slider_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/install-slider-5.jpg.
        /// </summary>
        public static string Install_Slider_5 {
            get {
                return ResourceManager.GetString("Install_Slider_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/intro-1.jpg.
        /// </summary>
        public static string Intro_1 {
            get {
                return ResourceManager.GetString("Intro_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/intro-2.jpg.
        /// </summary>
        public static string Intro_2 {
            get {
                return ResourceManager.GetString("Intro_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/intro-3.jpg.
        /// </summary>
        public static string Intro_3 {
            get {
                return ResourceManager.GetString("Intro_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/intro-4.jpg.
        /// </summary>
        public static string Intro_4 {
            get {
                return ResourceManager.GetString("Intro_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/intro-5.jpg.
        /// </summary>
        public static string Intro_5 {
            get {
                return ResourceManager.GetString("Intro_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/intro-6.jpg.
        /// </summary>
        public static string Intro_6 {
            get {
                return ResourceManager.GetString("Intro_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/intro-7.jpg.
        /// </summary>
        public static string Intro_7 {
            get {
                return ResourceManager.GetString("Intro_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/manual-bottom.jpg.
        /// </summary>
        public static string Manual_Bottom {
            get {
                return ResourceManager.GetString("Manual_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/manual-top.jpg.
        /// </summary>
        public static string Manual_Top {
            get {
                return ResourceManager.GetString("Manual_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu-en.jpg.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c1.jpg.
        /// </summary>
        public static string Menu_R6_C1 {
            get {
                return ResourceManager.GetString("Menu_R6_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c1-up.jpg.
        /// </summary>
        public static string Menu_R6_C1_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C1_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c10.jpg.
        /// </summary>
        public static string Menu_R6_C10 {
            get {
                return ResourceManager.GetString("Menu_R6_C10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c10-up.jpg.
        /// </summary>
        public static string Menu_R6_C10_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C10_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c11.jpg.
        /// </summary>
        public static string Menu_R6_C11 {
            get {
                return ResourceManager.GetString("Menu_R6_C11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c11-up.jpg.
        /// </summary>
        public static string Menu_R6_C11_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C11_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c12.jpg.
        /// </summary>
        public static string Menu_R6_C12 {
            get {
                return ResourceManager.GetString("Menu_R6_C12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c12-up.jpg.
        /// </summary>
        public static string Menu_R6_C12_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C12_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c2.jpg.
        /// </summary>
        public static string Menu_R6_C2 {
            get {
                return ResourceManager.GetString("Menu_R6_C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c2-up.jpg.
        /// </summary>
        public static string Menu_R6_C2_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C2_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c3.jpg.
        /// </summary>
        public static string Menu_R6_C3 {
            get {
                return ResourceManager.GetString("Menu_R6_C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c3-up.jpg.
        /// </summary>
        public static string Menu_R6_C3_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C3_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c4.jpg.
        /// </summary>
        public static string Menu_R6_C4 {
            get {
                return ResourceManager.GetString("Menu_R6_C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c4-up.jpg.
        /// </summary>
        public static string Menu_R6_C4_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C4_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c5.jpg.
        /// </summary>
        public static string Menu_R6_C5 {
            get {
                return ResourceManager.GetString("Menu_R6_C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c5-up.jpg.
        /// </summary>
        public static string Menu_R6_C5_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C5_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c6.jpg.
        /// </summary>
        public static string Menu_R6_C6 {
            get {
                return ResourceManager.GetString("Menu_R6_C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c6-up.jpg.
        /// </summary>
        public static string Menu_R6_C6_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C6_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c7.jpg.
        /// </summary>
        public static string Menu_R6_C7 {
            get {
                return ResourceManager.GetString("Menu_R6_C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c7-up.jpg.
        /// </summary>
        public static string Menu_R6_C7_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C7_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c8.jpg.
        /// </summary>
        public static string Menu_R6_C8 {
            get {
                return ResourceManager.GetString("Menu_R6_C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c8-up.jpg.
        /// </summary>
        public static string Menu_R6_C8_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C8_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c9.jpg.
        /// </summary>
        public static string Menu_R6_C9 {
            get {
                return ResourceManager.GetString("Menu_R6_C9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/menu_r6_c9-up.jpg.
        /// </summary>
        public static string Menu_R6_C9_Up {
            get {
                return ResourceManager.GetString("Menu_R6_C9_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/mx-v2.jpg.
        /// </summary>
        public static string Mx_V2 {
            get {
                return ResourceManager.GetString("Mx_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/mx-v2-up.jpg.
        /// </summary>
        public static string Mx_V2_Up {
            get {
                return ResourceManager.GetString("Mx_V2_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/mx244-app.jpg.
        /// </summary>
        public static string Mx244_App {
            get {
                return ResourceManager.GetString("Mx244_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/modules-slider-1.jpg.
        /// </summary>
        public static string Processors_Slider_1 {
            get {
                return ResourceManager.GetString("Processors_Slider_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/modules-slider-2.jpg.
        /// </summary>
        public static string Processors_Slider_2 {
            get {
                return ResourceManager.GetString("Processors_Slider_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/software-bottom.jpg.
        /// </summary>
        public static string Software_Bottom {
            get {
                return ResourceManager.GetString("Software_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/software-top.jpg.
        /// </summary>
        public static string Software_Top {
            get {
                return ResourceManager.GetString("Software_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/soho-slider-1.jpg.
        /// </summary>
        public static string Soho_Slider_1 {
            get {
                return ResourceManager.GetString("Soho_Slider_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/soho-slider-2.jpg.
        /// </summary>
        public static string Soho_Slider_2 {
            get {
                return ResourceManager.GetString("Soho_Slider_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/soho-slider-3.jpg.
        /// </summary>
        public static string Soho_Slider_3 {
            get {
                return ResourceManager.GetString("Soho_Slider_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/soho-slider-4.jpg.
        /// </summary>
        public static string Soho_Slider_4 {
            get {
                return ResourceManager.GetString("Soho_Slider_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/t20-slider-1.jpg.
        /// </summary>
        public static string T20_Slider_1 {
            get {
                return ResourceManager.GetString("T20_Slider_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/t20-slider-2.jpg.
        /// </summary>
        public static string T20_Slider_2 {
            get {
                return ResourceManager.GetString("T20_Slider_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/t20-slider-3.jpg.
        /// </summary>
        public static string T20_Slider_3 {
            get {
                return ResourceManager.GetString("T20_Slider_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/tma54bzt.jpg.
        /// </summary>
        public static string Tma54bzt {
            get {
                return ResourceManager.GetString("Tma54bzt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/tma54bzt-up.jpg.
        /// </summary>
        public static string Tma54bzt_Up {
            get {
                return ResourceManager.GetString("Tma54bzt_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/wireless-slider-1.jpg.
        /// </summary>
        public static string Wireless_Slider_1 {
            get {
                return ResourceManager.GetString("Wireless_Slider_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/wireless-slider-2.jpg.
        /// </summary>
        public static string Wireless_Slider_2 {
            get {
                return ResourceManager.GetString("Wireless_Slider_2", resourceCulture);
            }
        }
    }
}
