//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topppro.WebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MixersResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MixersResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topppro.WebSite.Resources.MixersResource", typeof(MixersResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download here the DMX24.4 PC Editor for Windows.
        /// </summary>
        public static string Dmx244_Editor_Windows {
            get {
                return ResourceManager.GetString("Dmx244_Editor_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download here the DMX24.4 Firmware Update (v 2.9) 16mb.
        /// </summary>
        public static string Dmx244_Firmware_Download {
            get {
                return ResourceManager.GetString("Dmx244_Firmware_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMX24.4 Firmware Update Instructions.
        /// </summary>
        public static string Dmx244_Firmware_Instructions {
            get {
                return ResourceManager.GetString("Dmx244_Firmware_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our new digital mixer is designed primarily for LIVE Audio Applications for the customer who wants all the power &amp; convenience digital processing &amp; instant recall offers, without giving up the familiarity, affordability &amp; ease of use of a traditional analog-style live mixer. Our digital mixer is powerful, affordable &amp; very easy to use!.
        /// </summary>
        public static string Dmx244_Message {
            get {
                return ResourceManager.GetString("Dmx244_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;BLUETOOTH!! &lt;/strong&gt;NOW AVAILABLE  WITH ORDER.
        /// </summary>
        public static string Mx_Bluetooth {
            get {
                return ResourceManager.GetString("Mx_Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed for live mixing.
        /// </summary>
        public static string MxDigital_Live_Mixing {
            get {
                return ResourceManager.GetString("MxDigital_Live_Mixing", resourceCulture);
            }
        }
    }
}
