//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topppro.WebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PacksResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PacksResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topppro.WebSite.Resources.PacksResource", typeof(PacksResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000W class D amplification.
        /// </summary>
        public static string i4K_Message {
            get {
                return ResourceManager.GetString("i4K_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our new &lt;b&gt;SOHO V4/8&lt;/b&gt; systems offer   uncompromising high quality pro audio in a highly efficient low profile footprint. The perfect choice for intimate to mid size spaces for groups or installation. With its sleek modern look, wood satellite columns and subwoofer finished in our special &lt;b&gt;SOHO&lt;/b&gt; paint process, and with an impressive total of 1400W (peak) in a stereo configuration, &lt;b&gt;SOHO&lt;/b&gt; excels where it counts, in the way it sounds. &lt;br/&gt;&lt;br/&gt; Available in two configurations,   &lt;b&gt;SOHO V4 &lt;/b&gt;wi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Soho_Message {
            get {
                return ResourceManager.GetString("Soho_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducing: &lt;b&gt;Topp Pro SOHO V4/V8 PA Systems&lt;/b&gt;.
        /// </summary>
        public static string Soho_Subtitle {
            get {
                return ResourceManager.GetString("Soho_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Sound…&lt;br /&gt;No Strings Attached!.
        /// </summary>
        public static string Soho_Title {
            get {
                return ResourceManager.GetString("Soho_Title", resourceCulture);
            }
        }
    }
}
