//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topppro.WebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProcessorsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcessorsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topppro.WebSite.Resources.ProcessorsResource", typeof(ProcessorsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;CS-LAN&lt;/b&gt; Ethernet Module..
        /// </summary>
        public static string Modules_HiRes_Cs_Lan {
            get {
                return ResourceManager.GetString("Modules_HiRes_Cs_Lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;CS-WM&lt;/b&gt; Wireless Master Module..
        /// </summary>
        public static string Modules_HiRes_Cs_Wm {
            get {
                return ResourceManager.GetString("Modules_HiRes_Cs_Wm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;CS-WSL&lt;/b&gt; Wireless Slave Module..
        /// </summary>
        public static string Modules_HiRes_Cs_Wsl {
            get {
                return ResourceManager.GetString("Modules_HiRes_Cs_Wsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;E-CS&lt;/b&gt; Ethernet Module..
        /// </summary>
        public static string Modules_HiRes_E_Cs {
            get {
                return ResourceManager.GetString("Modules_HiRes_E_Cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-ARK&lt;/b&gt; Microphone Preamplifier.
        /// </summary>
        public static string Modules_HiRes_Tac_Ark {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Ark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-BT2.1B&lt;/b&gt; Bluetooth Audio Receiver..
        /// </summary>
        public static string Modules_HiRes_Tac_Bt2 {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Bt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-MP3-R&lt;/b&gt; Records sounds to an USB key..
        /// </summary>
        public static string Modules_HiRes_Tac_Mp3_R {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Mp3_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-MP3-S&lt;/b&gt; Displays song title on display..
        /// </summary>
        public static string Modules_HiRes_Tac_Mp3_S {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Mp3_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-MP3-T&lt;/b&gt; Displays track number on display..
        /// </summary>
        public static string Modules_HiRes_Tac_Mp3_T {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Mp3_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-MX DSP&lt;/b&gt; 24-Bit FX Processor..
        /// </summary>
        public static string Modules_HiRes_Tac_Mx_Dsp {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Mx_Dsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-MX EQ&lt;/b&gt; 9 Band Graphic EQ..
        /// </summary>
        public static string Modules_HiRes_Tac_Mx_Eq {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Mx_Eq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;TAC-TMW 2.4R&lt;/b&gt; 2.4GHz Digital Wireless Receiver..
        /// </summary>
        public static string Modules_HiRes_Tac_Tmw {
            get {
                return ResourceManager.GetString("Modules_HiRes_Tac_Tmw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAC Modules are compatible with the following models.
        /// </summary>
        public static string Processors_Tac_Compatibility {
            get {
                return ResourceManager.GetString("Processors_Tac_Compatibility", resourceCulture);
            }
        }
    }
}
