//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topppro.WebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PublicResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublicResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topppro.WebSite.Resources.PublicResource", typeof(PublicResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Editor.
        /// </summary>
        public static string Audio_Editor {
            get {
                return ResourceManager.GetString("Audio_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Audio Processor.
        /// </summary>
        public static string Digital_Audio_Processor {
            get {
                return ResourceManager.GetString("Digital_Audio_Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Mixer.
        /// </summary>
        public static string Digital_Mixer {
            get {
                return ResourceManager.GetString("Digital_Mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Signal Processor.
        /// </summary>
        public static string Digital_Signal_Processor {
            get {
                return ResourceManager.GetString("Digital_Signal_Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Release.
        /// </summary>
        public static string Firmware_Release {
            get {
                return ResourceManager.GetString("Firmware_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Release Notes.
        /// </summary>
        public static string Firmware_Release_Notes {
            get {
                return ResourceManager.GetString("Firmware_Release_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Update.
        /// </summary>
        public static string Firmware_Update {
            get {
                return ResourceManager.GetString("Firmware_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility Tool For Firmware Update (iOS).
        /// </summary>
        public static string Firmware_Utility_Mac {
            get {
                return ResourceManager.GetString("Firmware_Utility_Mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Product Software.
        /// </summary>
        public static string Legacy_Product_Software {
            get {
                return ResourceManager.GetString("Legacy_Product_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Editor for Windows.
        /// </summary>
        public static string PC_Editor_For_Windows {
            get {
                return ResourceManager.GetString("PC_Editor_For_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Line Array System.
        /// </summary>
        public static string Professional_Line_Array_System {
            get {
                return ResourceManager.GetString("Professional_Line_Array_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmable Realtime Digital Speaker Management System.
        /// </summary>
        public static string Programable_Realtime_DSMS {
            get {
                return ResourceManager.GetString("Programable_Realtime_DSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CL-4 Software.
        /// </summary>
        public static string Software_CL4 {
            get {
                return ResourceManager.GetString("Software_CL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Update Instructions.
        /// </summary>
        public static string Software_Firmware_Update_Instructions {
            get {
                return ResourceManager.GetString("Software_Firmware_Update_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad &amp; iPhone Control App.
        /// </summary>
        public static string Software_IPad_IPhone_App {
            get {
                return ResourceManager.GetString("Software_IPad_IPhone_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Driver For Mac OS.
        /// </summary>
        public static string Software_Usb_Driver_MacOS {
            get {
                return ResourceManager.GetString("Software_Usb_Driver_MacOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check if you have the USB driver installed before applying the T20 software update. Your Mac will not detect the T20 if you don&apos;t have this driver installed.&lt;br/&gt;Please download the driver, install it and restart your Mac. Now you can go ahead with the software update..
        /// </summary>
        public static string Software_Usb_Driver_MacOS_Quote {
            get {
                return ResourceManager.GetString("Software_Usb_Driver_MacOS_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Driver for Windows.
        /// </summary>
        public static string Software_Usb_Driver_Windows {
            get {
                return ResourceManager.GetString("Software_Usb_Driver_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from here the most recent firmware and software to control your Topp Pro Hardware.
        /// </summary>
        public static string Softwere_Download {
            get {
                return ResourceManager.GetString("Softwere_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T32 USB Driver for Windows.
        /// </summary>
        public static string T32_Software_Usb_Driver_Windows {
            get {
                return ResourceManager.GetString("T32_Software_Usb_Driver_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update For Mac OS.
        /// </summary>
        public static string Update_For_MacOS {
            get {
                return ResourceManager.GetString("Update_For_MacOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update For Windows.
        /// </summary>
        public static string Update_For_Windows {
            get {
                return ResourceManager.GetString("Update_For_Windows", resourceCulture);
            }
        }
    }
}
