//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topppro.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ent_ProductResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ent_ProductResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topppro.Entities.Resources.Ent_ProductResource", typeof(Ent_ProductResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product.
        /// </summary>
        public static string _Caption {
            get {
                return ResourceManager.GetString("_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        public static string Entity_Enabled {
            get {
                return ResourceManager.GetString("Entity_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folder.
        /// </summary>
        public static string Entity_Folder {
            get {
                return ResourceManager.GetString("Entity_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual.
        /// </summary>
        public static string Entity_Manual {
            get {
                return ResourceManager.GetString("Entity_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Model.
        /// </summary>
        public static string Entity_Model {
            get {
                return ResourceManager.GetString("Entity_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Entity_Name {
            get {
                return ResourceManager.GetString("Entity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Priority.
        /// </summary>
        public static string Entity_Priority {
            get {
                return ResourceManager.GetString("Entity_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie.
        /// </summary>
        public static string Entity_Serie {
            get {
                return ResourceManager.GetString("Entity_Serie", resourceCulture);
            }
        }
    }
}
